
package itmo.soa.services.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "KillersServiceService", targetNamespace = "http://ws.services.soa.itmo/", wsdlLocation = "http://localhost:8082/ws/killers?wsdl")
public class KillersServiceService
    extends Service
{

    private final static URL KILLERSSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException KILLERSSERVICESERVICE_EXCEPTION;
    private final static QName KILLERSSERVICESERVICE_QNAME = new QName("http://ws.services.soa.itmo/", "KillersServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/ws/killers?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        KILLERSSERVICESERVICE_WSDL_LOCATION = url;
        KILLERSSERVICESERVICE_EXCEPTION = e;
    }

    public KillersServiceService() {
        super(__getWsdlLocation(), KILLERSSERVICESERVICE_QNAME);
    }

    public KillersServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), KILLERSSERVICESERVICE_QNAME, features);
    }

    public KillersServiceService(URL wsdlLocation) {
        super(wsdlLocation, KILLERSSERVICESERVICE_QNAME);
    }

    public KillersServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KILLERSSERVICESERVICE_QNAME, features);
    }

    public KillersServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KillersServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns KillersService
     */
    @WebEndpoint(name = "KillersServicePort")
    public KillersService getKillersServicePort() {
        return super.getPort(new QName("http://ws.services.soa.itmo/", "KillersServicePort"), KillersService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KillersService
     */
    @WebEndpoint(name = "KillersServicePort")
    public KillersService getKillersServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.services.soa.itmo/", "KillersServicePort"), KillersService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KILLERSSERVICESERVICE_EXCEPTION!= null) {
            throw KILLERSSERVICESERVICE_EXCEPTION;
        }
        return KILLERSSERVICESERVICE_WSDL_LOCATION;
    }

}
